version: "3"

services:

  server:
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - db
    entrypoint:
      - /start.sh
    environment:
      - DATABASE_URI=postgresql://localhost:5432/tracker'
    ports:
      - '5000:5000'
    expose:
      - '5000'
    container_name: server

  db:
    image: postgres:12.2-alpine


